.TH "GNU Health" 1 "2022\-10\-12" "4.2" "GNU Health : Free Health and Hospital Information System"

.SH NAME
GNU Health \- Free Health and Hospital Information System

.SH SYNOPSIS
\fBGNU Health\fR GNU Health is a Free/Libre project for health practitioners, 
health centers, research institutions and governments. 


.SH DESCRIPTION

GNU HEALTH is a Free / Libre, Health and Hospital Information System
that provides the following functionality:

Hospital Management Information System (HMIS)

* Electronic Medical Record (EMR)

* Health Information System (HIS)

* Laboratory Information System (LIS)


GNU Health combines the daily medical practice with state-of-the-art 
technology in bioinformatics and genetics. It provides a holistic approach 
to the  person, from the biological and molecular basis of disease to 
the social and environmental determinants of health.

GNU Health also manages the internal processes of a health institution, 
such as calendars, financial management, billing, stock management, 
pharmacies or laboratories (LIMS)

The GNU Health Federation allows to interconnect heterogeneous nodes
and build large federated health networks across a region, province
or country.



.SH HOMEPAGE
<\fIhttp://www.gnuhealth.org/\fR>.

.SH AUTHOR
Luis Falcon <\fIfalcon@gnuhealth.org\fR> and the GNU Health community


