#!/usr/bin/env bash

# gnuhealth-control
# The GNU Health control center 

##############################################################################
#
#    GNU Health: The Free Health and Hospital Information System
#    Copyright (C) 2008-2014  Luis Falcon <falcon@gnu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

VERSION="0.0.1"

usage()
{
    cat << EOF

usage: `basename $0` command [options]

Command:
 
  version : Show version
  backup  : Backup he gnuhealth kernel, attach dir and database
  update  : Download and install the patches
  status  : Check whether GNU Health is running

Options:

 --nobackup : Don't do a backup previous to the update. 
 --backdir  : destination directory for the backup file
 --dry-run  : Check, download and preview, but don't actually update process
 --database : database name to use with the update or backup command 

EOF
    exit 0
}

help()
{
    cat << EOF
    The GNU Health Control Center (gnuhealth-control) is the main tool for 
    administrative tasks of the GNU Health environment.
    
    It can perform backups and updates of the instance.
    
    Updates
    -------

    When gnuhealth-control is invoked with the update command, 
    it will update GNU Health components within the same major number
    The following components will be checked and updated if necessary

        - Trytond : Tryton server version
        - GNU Health patchsets

    This will be valid for version with the same major, minor numbers, for example
    2.8.x will look for the latest tryton updates and GNU Health updates
    associated to that release.

    GNU Health Control Center is available for release 2.8 and newer.
    You can get the latest version of GNU Health update at GNU
    ftp://ftp.gnu.org/gnu/health


EOF
    usage
    exit 0
}

get_current_values()
{
    # Bail out if no GNU Health profile exists
    if [ ! -e $HOME/.gnuhealthrc ]
    then
        echo "No GNU Health profile found !"
        exit 1
    fi
    
    # Stop if it can't find the GNU Health version
    if [ -z "$GNUHEALTH_VERSION" ]
    then
        echo "Could not find the GNU Health version env. variable"
        exit 1
    fi
    
    
    echo "Environment variables"
    echo "GNUHEALTH_VERSION = ${GNUHEALTH_VERSION}"
    echo "PYTHONPATH = $PYTHONPATH"
    
}

do_backup()
{
    local COMMAND=$1
    local BACKDATE=`date +%d-%m-%y_%H%M%S`
    local LOCKFILE="/tmp/.gnuhealth_backup.lock"
    local INFOFILE="/tmp/gnuhealth_backup.log"
    local BACKDIR=""
    local DB=""

    shift # Remove the command and deal only with the options
    
    if [ $# -ne 4 ]; then
        echo "Backup usage :"
        echo "gnuhealth-control backup --backdir <directory> --database <dbname>"
        exit
    fi

    for option in "$@"
    do
      case $option in
          --backdir ) BACKDIR=$2;;
          --database ) DB=$2 ;;
      esac
      shift
    done
    
    if [ -f $LOCKFILE ]
    then
            echo "$BACKDATE : Backup in progress or stale lock file found ..." | tee $INFOFILE
            exit
    fi

    touch $LOCKFILE

    
    shift
    
    
    # Backup start

    echo "$BACKDATE +++ START Database Backup" | tee $INFOFILE
    
    pg_dump $DB > $BACKDIR/backup\_$DB4\_$BACKDATE || exit -1 

    echo "$BACKDATE +++ Compressing Database Backup" | tee $INFOFILE

    gzip $BACKDIR/backup\_$DB\_$BACKDATE || exit -1
    
    echo "$BACKDATE +++  Creating compressed tarball with DB and GNU Health home directory" | tee $INFOFILE

    tar -cvf $BACKDIR/gnuhealth_backup\_$BACKDATE $HOME || exit -1

    echo "$BACKDATE Backup Successful" | tee $INFOFILE

    #Remove lock file
    rm $LOCKFILE


}

do_update()
{
   get_current_values
}
    
parse_command_line()
{
    if [ $# -eq 0 ]; then
        usage
    fi
    
    case $1 in
        version) echo $VERSION;;
        backup) do_backup $@;;
        update) do_update;;
        help) help;;
        *) echo $1: Unrecognized command; exit 1;;
    esac
}

parse_command_line $@



