Vagrant.configure("2") do |config|

  config.vm.box = 'gnuhealth'
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-puppet.box'

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
  end

  config.vm.synced_folder '../../', '/srv/gnuhealth'
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.provision :shell, :path => 'scripts/vagrant_bootstrap.sh'
end
